# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cubesviewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='update_user',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
